# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5195b417cb7167542215e84358d0e68c6bda7b36c9fd48f40dcfc468eadfbf0fcbbfe54191d92da43ccec932b1cab382f5f171b061a0853e554b2acdd347cddc

test:
  secret_key_base: 0c767a71efbe37add627f4ee83f972d744a380625e0a78f1cb7f4c621fef468d8cbeedf576555ec3bb536de3f09df32d510bd482018610d15d5da57fe3a5124e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
